name: jupyter-masterclass
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nodejs=12
  - jupyterlab=2
  - ipywidgets=7.5
  - seaborn=0.10
  - bqplot=0.12
  - matplotlib
  - pandas=1.0
  - voila=0.1
  - altair=4.1
  - tensorflow=2
  - sympy=1.4
  - scikit-learn=0.23
  - scikit-image=0.17