name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nodejs=12
  - jupyterlab=2
  - ipywidgets=7.5
  - seaborn=0.9
  - bqplot=0.12
  - matplotlib=3.1
  - pandas=0.25
  - voila=0.1
  # - altair=3.1
  # - tensorflow=1.13
  # - sympy=1.4
  # - scikit-learn=0.21
  # - scikit-image=0.15