name: jupyter-masterclass
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nodejs=12
  - jupyterlab=2.2.9
  - ipywidgets=7.5
  - seaborn=0.10
  - bqplot=0.12
  - matplotlib
  - pandas=1.0
  - voila=0.2.4
  - voila-vuetify=0.5.1
  - voila-gridstack=0.0.12
  - altair=4.1
  - sympy=1.4
  - ipyvuetify=1.5.1
  - scikit-learn=0.23
  - scikit-image=0.17